### PR TITLE
Some eggs with the bacon

### PR DESCRIPTION
**Pull request by mrange**
Added an egg command. Drawback of used approach is that you need to specify bacon command explicitly. I didn't figure out how to setup one command as default.

Anyway how to get the classic bacon experience we all know and love
```bash
dotnet run -c Release -- bacon
```

To have some egg with your bacon
```bash
dotnet run -c Release -- egg
```

### CODE REVIEW

**Comment by mrange** [comment]
I am talking with Spectre Patrik about how to capture the current terminal resolution to make the Canvas match that if no params given.

**Comment by ThindalTV** [comment]
I love it, but I would like just running "dotnet bacon" to use the dotnet bacon bacon as default.

**Comment by mrange** [comment]
I agree. I don't know how to setup system command line to do so

**Comment by ThindalTV** [comment]
Love it, approved!

**Pull request merged**
